
set MATLAB=D:\Matlab

D:\Matlab\toolbox\UnTransZynq\tools\make -f UnTrans_basicLQR.mk  TMW_EXTMODE_TESTING=0 MAT_FILE=1 COMBINE_OUTPUT_UPDATE_FCNS=1 INCLUDE_MDL_TERMINATE_FCN=1 MULTI_INSTANCE_CODE=0 MODELREF_TARGET_TYPE=NONE RELATIVE_PATH_TO_ANCHOR=.. OPTS="-DEXT_MODE -DON_TARGET_WAIT_FOR_START=0 -DTID01EQ=0"
